name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt install -y libelf-dev gcc libdwarf-dev libunwind-dev ninja-build python3 python3-pip python3-setuptools python3-wheel ninja-build elfutils libdw-dev
    - name: Install meson
      run: pip3 install meson
    - name: Configure
      run: meson _build
    - name: Compile
      run: ninja -C _build -j $(nproc)

  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: RafikFarhad/clang-format-github-action@v2.1.0
        with:
          sources: "src/**/*.h,src/**/*.c"
          style: file
